twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
            - 'bootstrap_5_layout.html.twig'

    globals:
       upload_folder: '%app.relative_path.image_directory%'


when@test:
    twig:
        strict_variables: true
